### ISSUE TITLE
Decoder_polar_SC_fast_sys -exception unhandled error when using (N,K)=(16,4)

### ISSUE THREAD

**Issue by Aishusiva** [aff3ct/aff3ct#100]
Does Decoder_polar_SC_fast_sys library accept (N,K)=(16,4)?

**Comment by bonben** [comment]
Hi @Aishusiva, please refer to https://github.com/aff3ct/aff3ct/issues/19#issuecomment-373424756 for a complete answer.

**Comment by Aishusiva** [comment]
Thanks a lot
