### ISSUE TITLE
Does Decoder_polar_ASCL_fast_CA_sys decoding technique in the AFFC3T library package, implement the PA-SSCL algorithm? 

### ISSUE THREAD

**Issue by Aishusiva** [aff3ct/aff3ct#113]
Does Decoder_polar_ASCL_fast_CA_sys decoding technique in the AFFC3T library package, implement the PA-SSCL algorithm?

**Comment by kouchy** [comment]
Yes, the `Decoder_polar_ASCL_fast_CA_sys` can be configured to either implement the `PA-SSCL` and `FA-SSCL` algorithm.
