### ISSUE TITLE
Problem using Encoder_turbo_product

### ISSUE THREAD

**Issue by Divya916947** [aff3ct/aff3ct#117]
I am trying to develop TPC encoder with BCH as the elementary block code. This is a portion of my code
`#include <memory>
#include<random>
#include<iostream>
#include<algorithm>
#include<string>
#include<math.h>
#include <stdlib.h>
#include <windows.h>
#include <ctype.h>
#include <omp.h>
#include<vector>
#include<aff3ct.hpp>

using namespace std;

#define K1 64
#define K2 64 
#define N1 127 
#define N2 127
#define t  10
#define n_ite 6

int main()
{
aff3ct::factory::Interleaver_core::parameters itl_params;
	itl_params.size = 64;

	auto interleaver_core = aff3ct::factory::Interleaver_core::build(itl_params);
	interleaver_core->init();
	auto interleaver = aff3ct::factory::Interleaver::build<B_32>(*interleaver_core);
	
	
	
	
	

	aff3ct::tools::BCH_polynomial_generator<> bch_poly(N1,t);
	aff3ct::module::Encoder_BCH<> enco_r(K1, N1,bch_poly);
	aff3ct::tools::BCH_polynomial_generator<> bch_polytwo(N1, t);
	aff3ct::module::Encoder_BCH<> enco_c(K1, N1, bch_polytwo);
	aff3ct::module::Encoder_turbo_product<> product(*interleaver, enco_r, enco_c);}`

I am getting exception error when using Decoder_turbo_product. Could you please help me on that?

**Comment by OlivierHartmann** [comment]
Hi Divya916947,
Please specify us the error you get with the stacktrace.
