### ISSUE TITLE
Does AFF3CT TPC FEC allow only BCH codes as elementary block codes?

### ISSUE THREAD

**Issue by Aishusiva** [aff3ct/aff3ct#119]
Could you please clarify if  AFF3CT TPC FEC allow only BCH codes as elementary block codes?

Thank you.

**Comment by OlivierHartmann** [comment]
Yes, only BCH: https://aff3ct.readthedocs.io/en/latest/user/simulation/parameters/codec/turbo_prod/codec.html
Feel free to develop new combinations for aff3ct.

**Comment by Aishusiva** [comment]
Okay. Thanks a lot.
