### ISSUE TITLE
simulationisgood but_PyBER_shows no_plots!

### ISSUE THREAD

**Issue by kumuds4** [aff3ct/aff3ct#12]
Olivier,
Thank you for help!
Yes! "Python3 pyBER.py & " did not work either. I tried on desktop and laptop both. I re-downloaded latest anaconda repo i.e. 
anaconda 3 4.4.0 for windows and is in Users/kumud
I have instructions from Adrien, am following that. 

On the other hand, simulation runs very fast in less than a minute. Please, see file attached. I am hoping an IT person would be able to help. I also am reading details. Am trying to add pyQt5 am not sure is needed. It seems that the only PATH is the problem. 

[simultnsyes_noplot!.pdf](https://github.com/aff3ct/aff3ct/files/1319435/simultnsyes_noplot.pdf)

**Comment by kumuds4** [comment]
Olivier ,
PyBER plot worked with Anaconda 2.7 what you have here. It is not working with Anaconda 3 with Python 3.6 Am trying to fix the problem using Linux like commands by downloading PyQt5. Simulations running well goes till the end of simulations. Missing is PyBER plot. I have done this trial since last 7 days. So, the update Anaocnda 3 with Python 3.6.1 or 3.6.2 has created a mess. 
Also, Kochy, this PyBER should be with aff3ct and PybER master should be changed to PyBER? Right!

**Comment by OlivierHartmann** [comment]
Hi kumuds,

Have you checked the PATH environment variable? It seems ti includes the path to the python2 binaries but not to the python3 binaries.
It seems also that, according to the picture you gave me, you are not running the command in the right order. You have inverted the two last.
> git clone https://github.com/aff3ct/PyBER.git
> cd PyBER
> git submodule update --init --recursive

Sorry I didn't understand the last question. Did you download something misspelled as PybER instead of PyBER ?

**Comment by kumuds4** [comment]
Olivier,

Thank you s much! I think I did run that way. Let me fix that. I have the
right PyBER now. When am back from the University, will take redo. I
believe it will work. Am taking the laptop to IT.
Once have results will post.
You all have a nice weekend!

Best,

-Kumud


****************************************************************
" A Mathematician is a device, turning coffee into Theorems"
-Alfréd Rényi, Budapest, Hungarian Academy of Sciences

****************************************************************
*Best regards!*

*Mrs. Kumud Singh_Altmayer Ph.D.*

*cell:(804) 564-6670 or (804) 564-6692*
*Ph./Fax:(804)658-0125*
*Email: ksa2te@virginia.edu <ksa2te@virginia.edu> alias: kumudsa@gmail.com
<kumudsa@gmail.com> *
