### ISSUE TITLE
Exception unhandled when using decode_siho

### ISSUE THREAD

**Issue by Divya916947** [aff3ct/aff3ct#122]
I am using AFF3CT library for encoding and decoding using turbo product codes.
This is my code.
`#include <memory>
#include<random>
#include<iostream>
#include<algorithm>
#include<string>
#include<math.h>
#include <stdlib.h>
#include <windows.h>
#include <ctype.h>
#include <omp.h>
#include<vector>
#include<aff3ct.hpp>

using namespace std;

#define K1 113
#define K2 113 
#define N1 127 
#define N2 127
#define T  2
#define n_ite 8
#define n_frames 127
#define decode_frames 1
#define decode_product_frames 1
vector<float>alpha = { 0.5,0.5,1,1,1,1,1.2,1.2,1.2,1.2,1.2,1.2,1.2,1.2,1.2,1.2 };
vector<float>beta = { 0.1,0.1,0.2,0.25,0.3,0.35,0.5,0.5,1.2,1.2,1.2,1.2,1.2,1.2,1.2,1.2 };
int n_least_reliable_positions=2;
int n_test_vectors=2;
int n_competitors=2;

int main()
{
	vector<int>ref_bits(12769);
	vector<int>enco_bits(16129);
/////////////////////////////////////////////////////BIT GENERATION///////////////////////////////////////////////////////////////////////////////////////

	std::random_device device;
	std::mt19937 generator(device());
	std::uniform_int_distribution<int> distribution(1, 100);

	for (int i = 0; i < 12769; ++i)
	{
		ref_bits[i] = distribution(generator) % 2;      //generates input data stream
	}

///////////////////////////////////////////////////////ENCODING///////////////////////////////////////////////////////////////////////////////////////////
	//interleaver using factory 
	aff3ct::factory::Interleaver_core::parameters itl_params;
	itl_params.size = 16129;
	itl_params.type = "ROW_COL";
	itl_params.n_cols = 127;
	auto interleaver_core = aff3ct::factory::Interleaver_core::build(itl_params);
	interleaver_core->init();
	auto interleaver = aff3ct::factory::Interleaver::build<B_32>(*interleaver_core);
	
	// BCH encoder using modules
	
	std::unique_ptr<aff3ct::tools::BCH_polynomial_generator<>> bch_poly;
	bch_poly= std::unique_ptr<aff3ct::tools::BCH_polynomial_generator<>>(new aff3ct::tools::BCH_polynomial_generator<>(N1,T));
	std::unique_ptr<aff3ct::module::Encoder_BCH<>> 	  enco_n;
	enco_n = std::unique_ptr<aff3ct::module::Encoder_BCH<>>(new aff3ct::module::Encoder_BCH<>(K1, N1, *bch_poly, n_frames));
	std::unique_ptr<aff3ct::module::Encoder_BCH<>> 	  enco_i;
	enco_i = std::unique_ptr<aff3ct::module::Encoder_BCH<>>(new aff3ct::module::Encoder_BCH<>(K1, N1, *bch_poly, n_frames));

	// TPC encoder using modules

	std::unique_ptr<aff3ct::module::Encoder_turbo_product<>> 	  encoder;
	encoder = std::unique_ptr<aff3ct::module::Encoder_turbo_product<>>(new aff3ct::module::Encoder_turbo_product<>(*interleaver, *enco_n, *enco_i));
	encoder->encode(ref_bits, enco_bits);

/////////////////////////////////////////////////////////////////////////MODULATION/////////////////////////////////////////////////////////////////////////////////////
	std::vector<float>modulationSymbols(16129, 0);       //initialize vector of modulation symbols
	double bpskValue;

	for (int i = 0; i < 16129; i++)                      //compute modulation symbols
	{
		bpskValue = -(2.0f * ((double)enco_bits[i]) - 1.0f);
		modulationSymbols[i] = (float)bpskValue;
	}

///////////////////////////////////////////////////////////////////////////DECODING/////////////////////////////////////////////////////////////////////////////////////

	//deinterleaver
	auto de_interleaver_core = aff3ct::factory::Interleaver_core::build(itl_params);
	de_interleaver_core->init();
	auto de_interleaver = aff3ct::factory::Interleaver::build<Q_32>(*de_interleaver_core);

	//BCH decoder
	std::unique_ptr<aff3ct::module::Decoder_BCH<>> 	  dec_n;
	dec_n = std::unique_ptr<aff3ct::module::Decoder_BCH<>>(new aff3ct::module::Decoder_BCH<>(K1, N1, T,decode_frames));
	std::unique_ptr<aff3ct::module::Decoder_BCH<>> 	  dec_i;
	dec_i = std::unique_ptr<aff3ct::module::Decoder_BCH<>>(new aff3ct::module::Decoder_BCH<>(K1, N1, T,decode_frames));
	       
	//chase pyndiah
	std::unique_ptr<aff3ct::module::Decoder_chase_pyndiah<>> 	  chase_r;
	chase_r = std::unique_ptr<aff3ct::module::Decoder_chase_pyndiah<>>(new aff3ct::module::Decoder_chase_pyndiah<>(K1, N1, decode_frames, *dec_n, *enco_n, n_least_reliable_positions, n_test_vectors, n_competitors));
	std::unique_ptr<aff3ct::module::Decoder_chase_pyndiah<>> 	  chase_c;
	chase_c = std::unique_ptr<aff3ct::module::Decoder_chase_pyndiah<>>(new aff3ct::module::Decoder_chase_pyndiah<>(K1, N1, decode_frames, *dec_i, *enco_i, n_least_reliable_positions, n_test_vectors, n_competitors));
	
	//TPC decoders using modules
	std::unique_ptr<aff3ct::module::Decoder_turbo_product<>> 	  decoder;
	decoder = std::unique_ptr<aff3ct::module::Decoder_turbo_product<>>(new aff3ct::module::Decoder_turbo_product<>( n_ite, alpha,*de_interleaver, *chase_r, *chase_c,beta,decode_product_frames));
	vector<B_32>dec_bits(12769);
	cout << "the value of K" << decoder->get_K() << "the value of N is" << decoder->get_N() << "the no. of frames are" << decoder->get_n_frames();
	int frame_id = -1;
	decoder->decode_siho(noisySymbols, dec_bits,frame_id);

	return 0;
}
`
I am getting exception unhandled error when using decode_siho. Could you please help me?

**Comment by OlivierHartmann** [comment]
Hi Divya916947,
Please specify us the error you get with the stacktrace.
