### ISSUE TITLE
Speed of Decoder_BCH_fast library

### ISSUE THREAD

**Issue by BonbenMathiew** [aff3ct/aff3ct#127]
I tried using the AFF3CT library functions to implement TPC encoding and decoding. I found that Decoder_BCH_fast performs slower than Decoder_BCH_std. I think from the file name, Decoder_BCH_fast should have a faster implementation. I appreciate if you could help me. Thank you:)

**Comment by kouchy** [comment]
Please avoid double post : https://github.com/aff3ct/aff3ct/issues/134#issuecomment-863078303.
