### ISSUE TITLE
Turbo_DB Code Rate and Puncturing

### ISSUE THREAD

**Issue by jdayana** [aff3ct/aff3ct#131]
Hi,

For DVB-RCS1 and DVB-RCS2, seven code rates are defined in the standard, R = 1/3, 2/5, 1/2, 2/3, 3/4, 4/5, 6/7.  And in the AFF3CT library, puncturing for the following code rates are available: R=2/5, R=1/2, R=2/3, R=4/5, with the nominal rate being 1/3. I am curious about the reason for this smaller group of code rates adopted. I hope to hear back from you.

Thanks,
Dayana

**Comment by kouchy** [comment]
Hi @jdayana,

I think the main reason is the time ;-).
But if you check the last version I think that @madellimac added more code rates.

I hope it helps.
