### ISSUE TITLE
Polar code question

### ISSUE THREAD

**Issue by Github-Shaw** [aff3ct/aff3ct#133]
In the project of Bootstrap,  K= 32, N=128 
I use the class Encode_polar to encode the ref_bits, 
and  m.modem ->modulate(enc_bits, symbols).
and then i use Decode_polar_SCL_fast_sys to decode (i don't change any bits int the symbols or enc_bits);
the ref_bits and the dec_bits is completely inconsistent

the decoder and encoder have the same frozenbits

could you help me please?

**Comment by kouchy** [comment]
Hi @Github-Shaw,

The `Decode_polar_SCL_fast_sys` output is `0` for zeros, and something else for ones (this is done for performance reasons). So if you want zeros and ones, you can easily parse the decoder output.

I hope it helps.
