### ISSUE TITLE
Invalid reference to deprecated simd_inter_frame_level

### ISSUE THREAD

**Issue by GitLuc1** [aff3ct/aff3ct#136]
Just a minor issue or legacy code.
Following LDPC headers reference **this->simd_inter_frame_level**, which has been removed from  aff3ct/include/Module/Decoder/Decoder.hpp and elsewhere in commit 37254f0ffea1912471fd5732b2403a3acf1531c8.

Include headers:
include/Module/Decoder/LDPC/BP/Horizontal_layered/Decoder_LDPC_BP_horizontal_layered_inter.hxx
include/Module/Decoder/LDPC/BP/Vertical_layered/Decoder_LDPC_BP_vertical_layered_inter.hxx
include/Module/Decoder/LDPC/BP/Flooding/Decoder_LDPC_BP_flooding_inter.hxx
(include/Module/Decoder/RSC/BCJR/Inter_intra/Decoder_RSC_BCJR_inter_intra.hxx)

I'm not sure what you want to do with it, thus I can't suggest a code change.
Thank you for the good work!

**Comment by kouchy** [comment]
Hi @GitLuc1,

Sorry for the latency, I fixed that in commit https://github.com/aff3ct/aff3ct/commit/80eb5a706c4554a071af013b8edc4b38fced85af (development branch).

Best
