### ISSUE TITLE
[question] Is there a module for Viterbi decoder?

### ISSUE THREAD

**Issue by joepol** [aff3ct/aff3ct#139]
Hi , I didn't find an implementation for convolutional encoder + Viterbi decoder, does it exist? or, is there a way to configure `Decoder_maximum_likelihod`  \ other modules to achieve this?

Thanks for your help, your library is wonderful!

**Comment by kouchy** [comment]
Hi @joepol,

For now, the Viterbi decoder has not been implemented in AFF3CT. However, it would be great to have it, I agree.

Best
