### ISSUE TITLE
Creating .alist files.

### ISSUE THREAD

**Issue by Divya916947** [aff3ct/aff3ct#141]
Hi,
I am planning to use DVBS2X standard codes in LDPC FEC library. Could you assist me on how to create the .alist file?
Thank you.

**Comment by kouchy** [comment]
You can check this link : https://aff3ct.readthedocs.io/en/latest/user/simulation/parameters/codec/ldpc/decoder.html#dec-h-path-image-required-argument

**Comment by Divya916947** [comment]
Thanks a lot.
How to save it in .alist format?
