### ISSUE TITLE
Decoding performance of Decoder_LDPC_BP_flooding_SPA

### ISSUE THREAD

**Issue by Divya916947** [aff3ct/aff3ct#142]
Hi,

I simulated Decoder_LDPC_BP_flooding_SPA. The decoding throughput comes around 1Mbps.I could see that the performance is not as high as the polar decoding libraries. Is it because of using exponentials in check node updates.

Thank you.

**Comment by kouchy** [comment]
You should use inter-frame SIMD implementations to reach higher throughput. You can use MS approximation to speedup the computations.
