### ISSUE TITLE
notissue_question_rather!

### ISSUE THREAD

**Issue by kumuds4** [aff3ct/aff3ct#15]
Am running for 8692 and 4096, keeps running. Similarly tried 3072 and 4096 didn't work. I mean the simulation does not end. I stopped using control^C twice but then no plot? Any idea?
Downloaded rather cloned decoder simulations that is new. May I have instructions how to work in Windows 10. 
Am in process to have installed Linux in one or two weeks.
Thank you again for all help!

**Comment by OlivierHartmann** [comment]
Please show us what you get. We do not understand your question.
