### ISSUE TITLE
QAM Demodulation Algorithm Implemented

### ISSUE THREAD

**Issue by ipapal** [aff3ct/aff3ct#191]
Hello,

Regarding the Soft Demodulation of QAM Constellations (that requres the calcualtion of LLRs), which algorithm is implemented in the library (Approximate LLR etc.)? I suppose the `FAST` implementation uses the same algorithm with the `STD` one, just with SIMD commands optimizations. I have tried reverse engineering the Demodulation function, but i can't quite understand to which algorithm it refers.

Thanks

**Comment by rtajan** [comment]
Hello @ilpapal,

The Soft QAM demodulation implementation can be found in [Modem_generic.hxx#L185](https://github.com/aff3ct/aff3ct/blob/8fa65a3ca9b0dcdd3d544363bc692d4f85f6f718/include/Module/Modem/Generic/Modem_generic.hxx#L185
).
It is called "Maximum A Posteriori symbol-to-bit metric calculator" in "Channel codes: classical and modern" of Ryan & Lin (Chapter 15 pp 637 in my version of the book).

 Depending on the command line options, the max* operator steps can be replaced by max operators or some other approximations, [see here.](https://aff3ct.readthedocs.io/en/latest/user/simulation/parameters/modem/modem.html#mdm-max)

Regarding the fast implementation, I agree it should be the same algorithm as the STD one but using SIMD optimizations.

**Comment by ipapal** [comment]
Thank you very much!
