### ISSUE TITLE
Cannot Run 5G Polar Simulation

### ISSUE THREAD

**Issue by crampart** [aff3ct/aff3ct#193]
I'm attempting to recreate the reference 5G polar code in the error_rate_references repo [here](https://github.com/aff3ct/error_rate_references/blob/021a9e0851720071bb3e22517744b688413bb6d5/POLAR/AWGN/BPSK/SC/Polar_N1024_K512_SC_5G_intra_p32.txt)

I stripped down the command from the reference output, as I don't have the library compiled for the "fast" implementations. The resulting invocation was 
`aff3ct -C "POLAR" -K "512" -N "1024" -m "1.0" -M "4.0" --dec-type "SC" --enc-fb-gen-method "5G"`
This results in a thrown exception:
`(EE) In the '~/Documents/projects/aff3ct/src/Tools/Code/Polar/Frozenbits_generator/Frozenbits_generator_5G.cpp' file at line 43 ('evaluate' function): "'' file does not exist."`

Note that the 'file' that it is looking for is an empty string. To my understanding, no file should be needed unless `--enc-fb-gen-method` is set to `FILE`.

**Comment by kouchy** [comment]
Hi @crampart,

On which system are you running AFF3CT and how did you compile it?

The 5G frozen bit generator is looking for the following file: `conf/cde/awgn_polar_codes/5G/N_1024.pc`.
Depending from where you are executing the AFF3CT binary it could fail to find the previous file.

The safest way is to run AFF3CT from the build folder: `./bin/aff3ct ...`

**Comment by crampart** [comment]
Running aff3ct from the bin directory resolves the issue, thanks!

The hard-coded file path complicates things a bit on our end. Is the following invocation equivalent?

`aff3ct -C "POLAR" -K "512" -N "1024" -m "1.0" -M "4.0" --dec-type "SC" -enc-fb-gen-method "FILE"  --enc-fb-awgn-path ${CONF_PATH}/N_1024.pc`

Or does the `5G` value have other side effects? (assuming, of course, that CONF_PATH is pointing to the correct directory)

**Comment by kouchy** [comment]
Unfortunately this is not equivalent :-(.

Have a look at this : https://github.com/aff3ct/aff3ct/blob/development/src/Tools/Code/Polar/Frozenbits_generator/Frozenbits_generator_5G.cpp#L37-L53.

However there is an environment variable you can use to specify the root path of the configuration files : `AFF3CT_CLI_PATH`

**Comment by crampart** [comment]
That path variable is perfect, thanks again!
