### ISSUE TITLE
Quantizer in Polar Codes

### ISSUE THREAD

**Issue by YangZhiyu1994** [aff3ct/aff3ct#26]
Hi,
  I would like to know if I want to use Quantizer in Polar codes, which command line should I use?

Thank you

**Comment by OlivierHartmann** [comment]
Hi YangZhiyu1994,

To use the quantizer you need first to run AFF3CT in 8 or 16 bits of precision. Use the argument --sim-prec (or -p) to set it. Then when you will display the help again (-h), you will see the quantizer parameters: mainly --qnt-bits and  --qnt-dec.

Olivier
