### ISSUE TITLE
Turbo coded SCMA in Rayleigh channel. Needs review

### ISSUE THREAD

**Issue by klimentyev** [aff3ct/aff3ct#36]
I couldn't obtain the results from paper: https://arxiv.org/pdf/1804.05814
Fig. 13 (c). It's Rayleigh channel with 1/3 turbo code rate and 2048 bits information coded block.
Also I tried to repeat my results from my MATLAB model for 1024 bits. In AFF3CT, BER and BLER are higher.

**Comment by klimentyev** [comment]
The example from paper. At SNR ~5 dB, BLER ~ 5e-2...5e-1. But I've results

`./aff3ct-2.2.0 --sim-type "BFER" -C "TURBO" -K "2048" -m "0" -M "6.00" -s "1" --enc-sub-std LTE --chn-type "RAYLEIGH" --chn-implem FAST --mdm-type "SCMA" --mdm-ite "5" -i "4" --mnt-max-fe "100" --src-fra "6" --dec-sf-type "LTE_VEC" --mdm-codebook "conf/mod/SCMA/CS1.cb"`

```
# ---------------------||------------------------------------------------------||---------------------
#  Signal Noise Ratio  ||   Bit Error Rate (BER) and Frame Error Rate (FER)    ||  Global throughput  
#         (SNR)        ||                                                      ||  and elapsed time   
# ---------------------||------------------------------------------------------||---------------------
# ----------|----------||----------|----------|----------|----------|----------||----------|----------
#     Es/N0 |    Eb/N0 ||      FRA |       BE |       FE |      BER |      FER ||  SIM_THR |    ET/RT 
#      (dB) |     (dB) ||          |          |          |          |          ||   (Mb/s) | (hhmmss) 
# ----------|----------||----------|----------|----------|----------|----------||----------|----------
      -0.01 |     0.00 ||      168 |   109108 |      168 | 3.17e-01 | 1.00e+00 ||    0.781 | 00h00'00   
       0.99 |     1.00 ||      174 |   104456 |      174 | 2.93e-01 | 1.00e+00 ||    0.901 | 00h00'00   
       1.99 |     2.00 ||      186 |    99709 |      186 | 2.62e-01 | 1.00e+00 ||    0.959 | 00h00'00   
       2.99 |     3.00 ||      186 |    81574 |      186 | 2.14e-01 | 1.00e+00 ||    0.954 | 00h00'00   
       3.99 |     4.00 ||      186 |    36354 |      183 | 9.54e-02 | 9.84e-01 ||    0.957 | 00h00'00   
       4.99 |     5.00 ||     1116 |     1149 |      112 | 5.03e-04 | 1.00e-01 ||    0.954 | 00h00'02   
       5.99 |     6.00 ||    15750 |        0 |        0 | 3.10e-08 | 6.35e-05 ||    0.981 | 00h00'32  x
```
I've BLER around zero at 6 dB instead of 1e-3, if at 5 db BLER is high (~1e-1). Maybe it's due to codebook properties and paper authors used another. Also, stopping criterion would be different...

What if the Rayleigh model for SCMA in AFF3CT? Does each user has independent channel coefficient on each resource? So for every SCMA codeword we have 2 different channel coefficient (for 2 non-zero elements). Or every user has 2 identical coefficients?

**Comment by klimentyev** [comment]
This question appeared their other :) Do you compare BER performance SCMA and 8-PSK? The system have the same overall spectrum efficiency (3 bit/s/Hz). But BLER in Rayleigh channel for SCMA is worse. Where is the SCMA gain?))) We see beautiful figures in papers and presentation with SCMA gain. I think that researchers uses JDD decoders (joint demodulation and detection of SCMA), so information is exchanged between MPA decoder and turbo decoder. In additional, they investigate multi-path channel, but we used Rayleigh model. And so.

`./aff3ct-2.2.0 --sim-type "BFER" -C "TURBO" -K "2048" -m "4.00" -M "4.00" -s "1" --enc-sub-std LTE --chn-type "RAYLEIGH" --chn-implem FAST -i "4" --mnt-max-fe "1000"  --dec-sf-type "LTE_VEC" --mdm-type "PSK" --mdm-bps "3"`

```
# ---------------------||------------------------------------------------------||---------------------
#  Signal Noise Ratio  ||   Bit Error Rate (BER) and Frame Error Rate (FER)    ||  Global throughput  
#         (SNR)        ||                                                      ||  and elapsed time   
# ---------------------||------------------------------------------------------||---------------------
# ----------|----------||----------|----------|----------|----------|----------||----------|----------
#     Es/N0 |    Eb/N0 ||      FRA |       BE |       FE |      BER |      FER ||  SIM_THR |    ET/RT 
#      (dB) |     (dB) ||          |          |          |          |          ||   (Mb/s) | (hhmmss) 
# ----------|----------||----------|----------|----------|----------|----------||----------|----------
       3.99 |     4.00 ||   461883 |     3657 |     1000 | 3.87e-06 | 2.17e-03 ||    7.045 | 00h02'14  
```

For 8-PSK BLER = 2.2e-3 and for SCMA BLER = 9.9e-1 at SNR = 4 dB.

It's very interesting.

**Comment by kouchy** [comment]
Hi @klimentyev,

First I want to tell you that I do not have your expertise in SCMA algorithms, my comprehension is quite naive.

I quickly checked the paper and it appears that `N = 2028` so `K = 672` (where you set `K = 2048`).
`N = 3 * K + 12` (tail bits).

I ran a simulation with `K = 672` like in the paper:
```
aff3ct --sim-type "BFER" -C "TURBO" -K "672" -m "5" -M "6.00" -s "0.1" --enc-sub-std LTE --chn-type "RAYLEIGH" --chn-implem FAST --mdm-type "SCMA" --mdm-ite "5" -i "4" --mnt-max-fe "100" --src-fra "6" --dec-sf-type "LTE_VEC" --mdm-codebook "conf/mod/SCMA/CS1.cb"
```

```
# ---------------------||------------------------------------------------------||---------------------
#  Signal Noise Ratio  ||   Bit Error Rate (BER) and Frame Error Rate (FER)    ||  Global throughput  
#         (SNR)        ||                                                      ||  and elapsed time   
# ---------------------||------------------------------------------------------||---------------------
# ----------|----------||----------|----------|----------|----------|----------||----------|----------
#     Es/N0 |    Eb/N0 ||      FRA |       BE |       FE |      BER |      FER ||  SIM_THR |    ET/RT 
#      (dB) |     (dB) ||          |          |          |          |          ||   (Mb/s) | (hhmmss) 
# ----------|----------||----------|----------|----------|----------|----------||----------|----------
       4.97 |     5.00 ||      678 |     2308 |      107 | 5.07e-03 | 1.58e-01 ||    0.294 | 00h00'01   
       5.07 |     5.10 ||      876 |     1953 |      104 | 3.32e-03 | 1.19e-01 ||    0.302 | 00h00'01   
       5.17 |     5.20 ||     1074 |     2141 |      103 | 2.97e-03 | 9.59e-02 ||    0.302 | 00h00'02   
       5.27 |     5.30 ||     2094 |     1607 |      100 | 1.14e-03 | 4.78e-02 ||    0.302 | 00h00'04   
       5.37 |     5.40 ||     3192 |     1448 |      100 | 6.75e-04 | 3.13e-02 ||    0.305 | 00h00'07   
       5.47 |     5.50 ||     4980 |     1651 |      100 | 4.93e-04 | 2.01e-02 ||    0.304 | 00h00'11   
       5.57 |     5.60 ||     8820 |     1352 |      100 | 2.28e-04 | 1.13e-02 ||    0.293 | 00h00'20   
       5.67 |     5.70 ||    15822 |      962 |      100 | 9.05e-05 | 6.32e-03 ||    0.297 | 00h00'35   
       5.77 |     5.80 ||    23694 |      932 |      100 | 5.85e-05 | 4.22e-03 ||    0.298 | 00h00'53   
       5.87 |     5.90 ||    45480 |     1063 |      100 | 3.48e-05 | 2.20e-03 ||    0.299 | 00h01'42   
       5.97 |     6.00 ||    86982 |      706 |      100 | 1.21e-05 | 1.15e-03 ||    0.301 | 00h03'14   
# End of the simulation.
```

The results look very close to the red curve of the Fig. 13. (c). Is it what you are expecting?

I'm not sure to understand your question about the Rayleigh model. I can tell you that the following part of the code is executed when running SCMA + Rayleigh channel :

https://github.com/aff3ct/aff3ct/blob/v2.2.2/src/Module/Channel/Rayleigh/Channel_Rayleigh_LLR.cpp#L77-L90

I hope it helps.

**Comment by klimentyev** [comment]
@kouchy thx! It's my mistake. I read as 2048 because in my papers K is code block size and 2048 is an information block size from LTE standard (e.g., fig. BER Performance in https://www.mathworks.com/help/comm/examples/parallel-concatenated-convolutional-coding-turbo-codes.html). Of course, Nc = 2028 in the paper.

Excuse for troubling. Everything is correct. I asked a series of questions on SCMA theory to the authors of the paper. The 8-PSK system is still better.

P.S.
`./aff3ct --sim-type "BFER" -C "TURBO" -K "512" -m "1.5" -M "1.5" -s "0.5" --enc-sub-std "LTE" -i "3" --dec-sf-type "LTE_VEC" --dec-sub-implem FAST --dec-sub-max "MAX" --mnt-max-fe "1000"`

```
 ---------------------||------------------------------------------------------||---------------------
#  Signal Noise Ratio  ||   Bit Error Rate (BER) and Frame Error Rate (FER)    ||  Global throughput  
#         (SNR)        ||                                                      ||  and elapsed time   
# ---------------------||------------------------------------------------------||---------------------
# ----------|----------||----------|----------|----------|----------|----------||----------|----------
#     Es/N0 |    Eb/N0 ||      FRA |       BE |       FE |      BER |      FER ||  SIM_THR |    ET/RT 
#      (dB) |     (dB) ||          |          |          |          |          ||   (Mb/s) | (hhmmss) 
# ----------|----------||----------|----------|----------|----------|----------||----------|----------
      -3.31 |     1.50 ||    74972 |     8639 |     1000 | 2.25e-04 | 1.33e-02 ||   25.284 | 00h00'01
```
The result is close to MATLAB, where BER is 1e-4.

**Comment by klimentyev** [comment]
@kouchy
Yes, I used "true" version of APP calculation and, but didn't remove the scaling factor.
Thx!
