### ISSUE TITLE
Please see issues with install on Windows 10

### ISSUE THREAD

**Issue by kumuds4** [aff3ct/aff3ct#4]
Hello,
I did get message from Adrien. It is giving same error. I have MinGw64, g++, cygwin and MS visual C++. I also downloaded gcc and g++ but nothing works.  Right now, have Windows only. I may have eventually Linux .  I have Cmake and aff3ct in my users/document folder as suggested by Adrien. Still could not run. 
To me it seems that the command in ~/.bashrc what is there for gcc an C++ is not in right path. 
I really would like to run Polar codes in AWGN. 

Thank you!
-Kumud

**Comment by kouchy** [comment]
This post is related to this one: https://github.com/aff3ct/aff3ct/issues/3
