### ISSUE TITLE
Run Polar Code after Installation 

### ISSUE THREAD

**Issue by marielacbv** [aff3ct/aff3ct#44]
Dear all,
I am  working with the simulator at my university. I am using the codes in https://github.com/aff3ct/aff3ct
The installation went fine; however I am not able to run the polar simulation using this: aff3ct -C "POLAR" -K 1723 -N 2048 -m 1.0 -M 4.0 -s 1.0
It says thath the command aff3ct is not found
I am using ubuntu and my directory is the build file in affect file
Regards

**Comment by kouchy** [comment]
Hi @marielacbv,

If you just compiled AFF3CT, assuming you are in the `AFF3CT_root/build/` directory, you have to execute the binary like this : `./bin/aff3ct -C "POLAR" -K 1723 -N 2048 -m 1.0 -M 4.0 -s 1.0`.

I hope it helps.
