### ISSUE TITLE
Command for Turbo

### ISSUE THREAD

**Issue by Shivani3094** [aff3ct/aff3ct#46]
Hi,

I am trying to use AFF3CT for turbo command.
The polar command is :
aff3ct-2.3.5.exe -C "POLAR" -K 1723 -N 2048 -m 1.0 -M 4.0 -s 1.0

but when i try to use the same for Turbo by modifying from polar to turbo as follows i am getting an error:
aff3ct-2.3.5.exe -C "TURBO" -K 1723 -N 2048 -m 1.0 -M 4.0 -s 1.0

Kindly let me now what kind of command and parameters are required for turbo.

**Comment by bonben** [comment]
Hi @Shivani3094.

I think the error you get is:
```bash
(EE) In the '/build/aff3ct-uYX5nc/aff3ct-2.3.5-58-g96427b0/src/Tools/Interleaver/LTE/Interleaver_core_LTE.cpp' file at line 223 ('gen_lut' function): "There is no LTE f_1 and f_2 parameters for 'size' = 1723."
```
There is a limited amount of values of K in the LTE standard, which is default for turbo codes in AFF3CT.

I think what you need is some example command lines for Turbo codes. 

You can find some in our reference database. For instance, if you want to consider LTE codes: https://github.com/aff3ct/error_rate_references/tree/master/TURBO/AWGN/BPSK/RSC_RSC/BCJR/LTE

You can also find example command lines in the comparator of the website : http://aff3ct.github.io/comparator.html?curve0=0e33c33&xaxis=Eb%2FN0&yaxes=BER%2CFER

![drawing](https://user-images.githubusercontent.com/6402741/68926056-e0fd5e00-0784-11ea-9032-2656b7077e58.png)

Regards.
