### ISSUE TITLE
Simple encode / decode example

### ISSUE THREAD

**Issue by wkunice** [aff3ct/aff3ct#71]
If one wants to use the aff3ct to do just encoding a block and decoding a block (not link simulation).  Is there an example of this? Thx.

**Comment by kouchy** [comment]
Hi @wkunice,

There is no example with only a transmitter or a receiver.
But if you take the `bootstrap` example and for instance you want to make a basic transmitter, you only need to keep the following highlighted lines : https://github.com/aff3ct/my_project_with_aff3ct/blob/b866bbd4352a3baa89fdb673137383408038a206/examples/bootstrap/src/main.cpp#L92-L94.

The `b.symbols` vector will contains the symbols to emit.

I hope it helps.

**Comment by wkunice** [comment]
Thanks that did help.
