### ISSUE TITLE
How to simulate CA-SCL decoder

### ISSUE THREAD

**Issue by anubhavguleria47** [aff3ct/aff3ct#80]
I used following command to simulate SCL decoding pipeline: 
./aff3ct` --sim-type "BFER" --sim-prec 32 --sim-noise-type "EBN0" -C "POLAR" --enc-type "POLAR" --enc-fb-gen-method "5G"  --dec-type "SCL" --dec-lists 4 -K 512 -N 1024 --src-type "RAND" --sim-noise-min -2 --sim-noise-max 4 --sim-noise-step 0.5

However, I could not see how to run CA-SCL decoding pipeline. What parameter needs to be changed in above command?

**Comment by bonben** [comment]
Hello @anubhavguleria47 

In order to run CA-SCL, you just need to use the `--crc-poly` argument.
e.g. : 
```
./aff3ct` --sim-type "BFER" --sim-prec 32 --sim-noise-type "EBN0" -C "POLAR" --enc-type "POLAR" --enc-fb-gen-method "5G" --dec-type "SCL" --dec-lists 4 -K 512 -N 1024 --src-type "RAND" --sim-noise-min -2 --sim-noise-max 4 --sim-noise-step 0.5 --crc-poly 32-GZIP
```
You can see it documented here: https://aff3ct.readthedocs.io/en/latest/user/simulation/parameters/crc/crc.html#crc-type-crc-poly

Regards.
