### ISSUE TITLE
Using Lower values of static_level for Polar Codes.

### ISSUE THREAD

**Issue by anubhavguleria47** [aff3ct/aff3ct#82]
Hi,
In Decoder_polar_SC_fast_sys.hxx there static_level is defined as 6. Is setting this to lower values affect the correctness of Polar Codes?

Thanks

**Comment by bonben** [comment]
Hello @anubhavguleria47.

No, changing the static level won't aff3ct (!) the decoding performance of the decoder. It's only there for speed !

Regards.
