### ISSUE TITLE
unable to run aff3ct.exe

### ISSUE THREAD

**Issue by HindTh** [aff3ct/aff3ct#88]
Hi all,

I am tired to open aff3ct.exe but its window appears for a few seconds and then closed.
This is the last step of the installation. 
![aff3ctInstall](https://user-images.githubusercontent.com/73593830/97444209-effd0200-193c-11eb-822b-28a570abe603.png)

I don't know what is the problem or how can I fixed it. please there are any suggestions.

Thank you.

**Comment by kouchy** [comment]
Hi @HindTh,

Do you double click on `aff3ct.exe`? From the Windows graphic interface?

If it is the case, it is not the right usage of AFF3CT. AFF3CT is not a graphic application, it is a command line application and should be run from the command line.

I hope it helps.

**Comment by HindTh** [comment]
> Hi @HindTh,
> 
> Do you double click on `aff3ct.exe`? From the Windows graphic interface?
> 
> If it is the case, it is not the right usage of AFF3CT. AFF3CT is not a graphic application, it is a command line application and should be run from the command line.
> 
> I hope it helps.

Dear @kouchy 

I am run the program from "MinGW Command Prompt" but the problem still exists.

**Comment by HindTh** [comment]
I get this snapshot 
![aff3ctInstall2](https://user-images.githubusercontent.com/73593830/97448360-a4008c00-1941-11eb-9655-95a090b89833.png)

**Comment by kouchy** [comment]
Good, AFF3CT is working now. You can try to run it with some parameters like this:
```
aff3ct.exe -C "POLAR" -K 1723 -N 2048 -m 1.0 -M 4.0 -s 1.0
```
Please read the [documentation](https://aff3ct.readthedocs.io/en/latest/) to more advanced usage.

**Comment by HindTh** [comment]
> Good, AFF3CT is working now. You can try to run it with some parameters like this:
> 
> ```
> aff3ct-2.3.5.exe -C "POLAR" -K 1723 -N 2048 -m 1.0 -M 4.0 -s 1.0
> ```
> 
> Please read the [documentation](https://aff3ct.readthedocs.io/en/latest/) to more advanced usage.

Dear sir,

aff3ct may be working but it just flashing and close I cannot catch the window.
