### ISSUE TITLE
Memory error when running polar code in bootstrap example

### ISSUE THREAD

**Issue by Aishusiva** [aff3ct/aff3ct#90]
I tried using encoder_polar_sys and Decoder_polar_SC_fast_sys in the bootstrap example.I included the required arguments.But I am getting memory error when trying to build the program.

I am attaching the screenshots of changes I have made in the code
![image](https://user-images.githubusercontent.com/74765188/101427697-4f85fe80-393a-11eb-98da-3b8d6f452700.png)
![image](https://user-images.githubusercontent.com/74765188/101427727-5f9dde00-393a-11eb-96b4-e240723d3bcd.png)
![image](https://user-images.githubusercontent.com/74765188/101427752-6cbacd00-393a-11eb-8ff6-1eb4bb51d65f.png)
![image](https://user-images.githubusercontent.com/74765188/101427882-ab508780-393a-11eb-87c5-1cf2a3b9089c.png)

**Comment by ibarron9216** [comment]
Could you share the memory error message?
