### ISSUE TITLE
execution time when running bootstrap example

### ISSUE THREAD

**Issue by Aishusiva** [aff3ct/aff3ct#96]
I tried using Encoder_polar_sys and Decoder_polar_sc_fast_sys in the bootsrap example. The program runs fine till SNR=5,afterwhich it takes about 20 min to compute for the next SNR.I don't have this issue with other combinations of polar encoder and decoder .Could you please help me with this?

**Comment by kouchy** [comment]
Hi @Aishusiva,

I think this is normal, for each SNR value 100 erroneous frames are simulated. But when the SNR is high (5 dB for instance in your case) the number of necessary simulated frames grows exponentially.

I hope it helps.

**Comment by Aishusiva** [comment]
Thanks a lot.
